site_name: cupid_matching

site_url: https://github.pages.io/bsalanie

repo_url: https://github.com/bsalanie/cupid_matching

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
        # - navigation.expand
        - navigation.tabs
    custom_dir: "docs/overrides"

plugins:
    - search
    - mkdocstrings
    - git-revision-date
          
markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

nav:
    - Home: index.md
#    - Installation: installation.md
#    - Usage: usage.md
#    - Contributing: contributing.md
#    - FAQ: faq.md
    - Report Issues: https://github.com/bsalanie/cupid_matching/issues
    - API Reference:
          - min_distance: min_distance.md
          - min_distance_utils: min_distance_utils.md
          - poisson_glm: poisson_glm.md
          - poisson_glm_utils: poisson_glm_utils.md
          - entropy: entropy.md
          - choo_siow: choo_siow.md
          - choo_siow_gender_heteroskedastic: choo_siow_gender_heteroskedastic.md
          - choo_siow_heteroskedastic: choo_siow_heteroskedastic.md
          - nested_logit: nested_logit.md
          - ipfp_solvers: ipfp_solvers.md
          - matching_utils: matching_utils.md
          - utils: utils.md


 