name: docs
on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install --user -r requirements.txt
                  pip install --user .
#            - name: PKG-TEST
#              run: |
#                  python -m pytest tests/
            - run: python -m pip install --upgrade pip
            - run: pip install mkdocs-material mkdocstrings mkdocs-git-revision-date-plugin
            - run: mkdocs build
            - run: mkdocs gh-deploy --force
